models/base.py
"""
Base class handles serialization/deserialization by calling methods of a given database connection
The default connection is FirestoreClient
"""

from models.storage.firestore import FirestoreClient


class Base():
    """ Base Model """
    db_client = FirestoreClient()

    def __init__(self, *args, **kwargs):
        """ init """
        from uuid import uuid4
        for (k, v) in kwargs.items():
            setattr(self, k, v)
        if not kwargs.get('id'):
            self.id = str(uuid4())

    @classmethod
    def connection(cls):
        return Base.db_client.connected()

    @classmethod
    def get_by_class(cls):
        return Base.db_client.get_by_class(cls.__name__)
    
    @classmethod
    def get_by_id(cls, id):
        return Base.db_client.get_by_id(cls.__name__, id)
    
    @classmethod
    def get_by_attr(cls, attr, val):
        return Base.db_client.get_by_attr(cls.__name__, attr, val)
    
    def to_dict(self):
        """ return dictionary representation of object """
        return self.__dict__

    def save(self):
        print('saving')
        Base.db_client.save(self)

    @classmethod
    def update_attr_by_id(cls, id, attr, val):
        return Base.db_client.update_attr_by_id(cls, id, attr, val)

    def delete(self):
        Base.db_client.delete(self)
    
    @classmethod
    def delete_by_id(cls, id):
        Base.db_client.delete_by_id(cls, id)

models/product.py
from models.base import Base

class Product(Base):
    def __init__(self, *args, **kwargs):
        self.price = 0
        self.name = ''
        self.description = ''
        self.in_stock = 0
        self.image_url = 'https://media.istockphoto.com/photos/open-cardboard-box-picture-id173831957?k=6&m=173831957&s=612x612&w=0&h=Lia7nWeOi0dOBJElI8tRmfoMqEQ_sNBjKbydZoJ3V_w='
        super().__init__(*args, **kwargs)

api/__init__.py
from api.v1.products import *

api/v1/__init__.py
from flask import Blueprint

api_v1 = Blueprint("api", __name__, url_prefix="/api")

main.py
"""
ENTRY POINT
"""
from flask import Flask, jsonify, render_template, url_for
from flask_cors import (CORS, cross_origin)
from uuid import uuid4
from os import environ
from routes import *
from api import *


app = Flask(__name__)
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0
if "FLASK_SECRET_KEY" in environ:
    app.secret_key = environ["FLASK_SECRET_KEY"]
else:
    environ["FLASK_SECRET_KEY"] = str(uuid4())
CORS(app, resources={r"*": {"origins": "*"}})

app.register_blueprint(landing)
app.register_blueprint(storefront)
app.register_blueprint(api_v1)



"""
ERROR HANDLERS
"""

@app.errorhandler(400)
def bad_request(error) -> str:
    """
    Request is bad
    """
    return jsonify({"error": "Bad Request, https required"}), 400


@app.errorhandler(404)
def not_found(error) -> str:
    """
    Not found handler
    """
    return jsonify({"error": "Not found"}), 404


@app.errorhandler(403)
def Forbidden(error) -> str:
    """
    Forbidden handler
    """
    return jsonify({"error": "Forbidden"}), 403


@app.errorhandler(401)
def Unauthorized(error) -> str:
    """
    Unauthorized handler
    """
    return jsonify({"error": "Unauthorized"}), 401



if __name__ == '__main__':
    # This is used when running locally only. When deploying to Google App
    # Engine, a webserver process such as Gunicorn will serve the app. This
    # can be configured by adding an `entrypoint` to app.yaml.
    app.run(host='127.0.0.1', port=8080, debug=True)
# [END gae_python38_app]

routes/__init__.py
from routes.landing import *
from routes.store import *

routes/landing.py
from flask import render_template, Blueprint


landing = Blueprint("landing", __name__, url_prefix="/")

@landing.route('/', methods=['GET'], strict_slashes=False)
def index():
    return render_template('landing.html')

routes/store.py
from flask import render_template, Blueprint
import requests
from helpers import build_url


storefront = Blueprint("store", __name__, url_prefix="/store")

@storefront.route('/', methods=['GET'], strict_slashes=False)
def index():
    data = {}
    r = requests.get(build_url('api/products')).json()
    if not r.get('status') == 'OK':
        data['msg'] = 'API error'
    data['products'] = r.get('products')
    return render_template('store.html', data=data)

templates/base.html
<a href="{{ url_for('store.index') }}">products</a>

templates/landing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Simple E-commerce website"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"></link>
    <link rel="stylesheet" href="../static/styles.css"></link>
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Rozha+One&display=swap" rel="stylesheet">

    <title>Toastbrush</title>
  </head>
  
    <body>
        <div class="container">
            <div class="sidebar">
                <ul class="nav_list">
                    <li class="nav-item"><a href="#">Home</a></li>
                    <li class="nav-item"><a href="#about">About</a></li>
                    <li class="nav-item"><a href="{{ url_for('store.index') }}">Store</a></li>
                </ul>
            </div>
            <div class="hero">
                <div class="logo"><img src="../static/images/toast_brush_logo_circle-cropped.png" alt=""></div>
            </div>
            <div class="slogan">
                <h2>You Can't Brush What You Can't Touch</h2>
            </div>
            <div class="about" id="about">
                <div class="quote">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.                        
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus ultricies tristique nulla aliquet enim tortor. Massa sed elementum tempus egestas sed sed risus pretium. Quam viverra orci sagittis eu volutpat odio facilisis. Lorem ipsum dolor sit amet consectetur. Diam donec adipiscing tristique risus nec. Neque convallis a cras semper. Ut placerat orci nulla pellentesque dignissim enim sit amet.
                    </p>
                </div>
            </div>
            <div class="footer">
                <footer>© Makers Club 2021</footer>
            </div>
        </div>
    </body>
</html>